### ISSUE TITLE
Birthday without age shows 43

### ISSUE THREAD

**Issue by dschuermann** [PrivacyApps/birthday-calendar#52]
_Original author: alex.je...@gmail.com (April 23, 2013 08:42:12)_

<b>What steps will reproduce the problem?</b>
1.it shows even with original and custom labels 
<b>2.</b>
<b>3.</b>

<b>What is the expected output? What do you see instead?</b>
It should show without age. 

<b>What version of the product are you using? On what operating system?</b>
1.13 (14) on custom rom SlimBean 4.2.2 build 3

<b>Please provide any additional information below.</b>

_Original issue: http://code.google.com/p/birthday-adapter/issues/detail?id=50_

**Comment by ialokim** [comment]
This problem still persists for me with version 2.0, Contacts is showing the birthday without year, but the calendar event shows the age as 2019-1970=49.
@dschuermann Is this app still maintained? Is there a chance a PR would be merged if I find the time to look into it?

**Comment by dschuermann** [comment]
I think it is already fixed in https://github.com/SufficientlySecure/birthday-calendar/commit/0d535e44f3ae56ffe3f75836b8352de6b89f7355

I need to do a release, sry. Will put it on top of my TODO list.

**Comment by ialokim** [comment]
Okay, that would be great!

**Comment by Otiel** [comment]
Any ETA for a release with this fix?

**Comment by ialokim** [comment]
> I need to do a release, sry. Will put it on top of my TODO list.

Could we do anything to help you getting the release done?

**Comment by fgblomqvist** [comment]
@dschuermann any possibility this could get released?
